### ISSUE TITLE
Ramdisk won't boot

### ISSUE THREAD

**Issue by m1stadev** [dualbootfun/dualbootfun.github.io#1]
I'm trying to dual boot an iPod touch 6, with 12.4.6 as the main OS, and 12.4 as the secondary OS. However, no matter what I seem to try, the ramdisk will not boot. My process is the same as in the guide on the First Boot page, I decrypt the iBSS and iBEC with img4, patch out their signature checks (while also adding the "rd=md0 nand-enable-reformat=1 -restore -v" boot arguments), then create img4 files out of them with img4 and the IM4M I got from my shsh. I then create an img4 out of the devicetree im4p, and the IM4M, while also changing the tag to rdtr. Then, I pack trustcache into an img4, and run these commands:
`irecovery -f iBSS.img4`
`irecovery -f iBEC.img4`
`irecovery -f ramdisk`
`irecovery -c ramdisk`
`irecovery -f devicetree.img4`
`irecovery -c devicetree`
`irecovery -f trustcache.img4`
`irecovery -c firmware`
`irecovery -f kernelcache.img4`
`irecovery -c bootx`
After I run these commands, nothing happens `irecovery -m` shows the device is still in recovery mode. I then tried starting a shell after entering pwned dfu mode, and uploading the files and running the commands from there. 
Something i've noticed is that when I upload trustcache, and run firmware, I don't get any reponse message, only this: `ea0f64a4253252:252`
When I run bootx, I get this:
```> bootx
ea0f64a4253252:252
Attempting to validate kernelcache @ <ptr>
9905b4edc794469:689
dce7b01f6ef60a3:188
7ab90c923dae682:397

**Comment by NotHereForTheDong** [comment]
loaded ramdisk at <ptr> of size 0x6151800, from image at <ptr>

iRecovery> /send devicetree.img4 
Sent: 32768 bytes - 32768 of 143172
Sent: 32768 bytes - 65536 of 143172
Sent: 32768 bytes - 98304 of 143172
Sent: 32768 bytes - 131072 of 143172
Sent: 12100 bytes - 143172 of 143172
[Device] Successfully uploaded file.

iRecovery> devicetree
ea0f64a4253252:308
loaded device tree at <ptr> of size 0x100000, from image at <ptr>

iRecovery> /send trustcache.img4 
Sent: 10361 bytes - 10361 of 10361
[Device] Successfully uploaded file.

iRecovery> firmware
ea0f64a4253252:308

///LaterOn///

iRecovery> bootx
ea0f64a4253252:308
7ab90c923dae682:486
9905b4edc794469:694
dce7b01f6ef60a3:185
7ab90c923dae682:447

Same issue that TrustCache doesn't seem to be initiating correctly.

**Comment by m1stadev** [comment]
This is due to me not compressing the kernel correctly, which the guide is updated to do.

**Comment by NotHereForTheDong** [comment]
too bad it still doesn't work. I always get "unable to mount outer volume" on three different devices when running apfs invert
