### ISSUE TITLE
No such volume when trying to run apfs_invert

### ISSUE THREAD

**Issue by NotHereForTheDong** [dualbootfun/dualbootfun.github.io#4]
Issue of device panics when booting Ramdisk with bootargs “rd=md0 nand-enable-reformat=1 -v”

Edit: found out this is due to apfs_invert not finding the disk properly. Attached terrible quality screenshot below

![BFDD8998-A365-4B70-B95F-27A33CCE4C4F](https://user-images.githubusercontent.com/52018850/79999488-f55b2a80-8489-11ea-8635-50e3fa7ec698.jpeg)

The interesting part is “ mounting outer volume (/dev/disk0s1 s4)” “device initialization failed” “nx_mount returned 2”.

The odd part is that this happens on both my a9 devices. One on iOS 12.4 and another on 13.3 . I have followed all the steps and this just keeps happening.

Also a side note is on iOS 13 you must use ldid2 to extract the entitlements of the original restore_externald and resign the fake binary with that xml otherwise it refuses to run at all.

""""

char *arg[] = {"apfs_invert", "-d","/dev/disk0s1","-s","8","-n","out.dmg", NULL}; // modify me if neeeded
    posix_spawn(&pid, "/System/Library/Filesystems/apfs.fs/apfs_invert",NULL, NULL, (char* const*)arg, NULL);
    waitpid(pid, &i, 0);

    char *arg2[] = {"mount_apfs","/dev/disk0s1s8","/mnt1", NULL}; // modify me if neeeded
    posix_spawn(&pid, "/System/Library/Filesystems/apfs.fs/mount_apfs",NULL, NULL, (char* const*)arg2, NULL);
    waitpid(pid, &i, 0);

"""

**Comment by 0nenZer0** [comment]
@NotHereForTheDong @Ralph0045 any good news on this? I'm also having same error in in iPhone6s N71AP ios13

**Comment by NotHereForTheDong** [comment]
@0nenZer0 
 No, there is another method coming soon to automate this. follow creator here https://mobile.twitter.com/mosk_i

**Comment by 0nenZer0** [comment]
@NotHereForTheDong OK noted.
