### ISSUE TITLE
Patching Bootchain fails on A10, iPhone9,3

### ISSUE THREAD

**Issue by NotHereForTheDong** [dualbootfun/dualbootfun.github.io#6]
When trying to send iBEC followed by later bootchain it states all images are invalid with irecovery.

I’m unsure of what the difference is as this process works very well for my A9 / A9X chips and have dualbooted them with no issues

Delaying boot for 0 seconds. Hit enter to break into the command prompt...
3974bfd3d441da3:1246
Entering recovery mode, starting command prompt
ea0f64a4253252:308
Memory image not valid
Device Tree image not valid
Kernelcache image not valid

**Comment by Ralph0045** [comment]
On A10+ (except A10x) iBoot must be sent twice and use go command to reload it, otherwise all images won't be valid

**Comment by NotHereForTheDong** [comment]
Oh ok that works very well now. Thanks for the clarification.
